### ISSUE TITLE
Add incoming midi filter capability

### ISSUE THREAD

**Issue by llloret** [llloret/sp_midi#19]
So that it is possible to filter out some messages, like midi clock.

**Comment by llloret** [comment]
Although perhaps it is best to do this at the higher level?

**Comment by samaaron** [comment]
I'm already filtering out clock and active sensing messages at the Erlang level. If this is somehow not efficient enough then we can look to moving it down to the C++ level.

**Comment by llloret** [comment]
Ok, I'll close this for now, then. Thank you
